language: objective-c
osx_image: xcode9

env:
  global:
    - WORKSPACE="OpenCC.xcworkspace"
    - SCHEME="OpenCC"
  matrix:
    - ACTION=test   PLATFORM=macOS      DESTINATION='platform=OS X'
    - ACTION=test   PLATFORM=iOS        DESTINATION='platform=iOS Simulator,name=iPhone 8'
    - ACTION=test   PLATFORM=tvOS       DESTINATION='platform=tvOS Simulator,name=Apple TV 4K'

before_script:
  - set -o pipefail

script:
  - xcodebuild $ACTION
    -workspace "$WORKSPACE"
    -scheme "$SCHEME"
    -destination "$DESTINATION" | xcpretty
