name: CI

on:
  # push:
  # pull_request:

jobs:
  Xcode:
    strategy:
      matrix:
        env:
          - platform: macOS
            destination: "platform=macOS"
            action: test
          - platform: iOS
            destination: "platform=iOS Simulator,name=iPhone 8"
            action: test
          - platform: tvOS
            destination: "platform=tvOS Simulator,name=Apple TV 4K"
            action: test
          - platform: watchOS
            destination: "platform=watchOS Simulator,name=Apple Watch Series 4 - 44mm"
            action: build
    runs-on: macOS-latest
    env:
      ACTION: ${{ matrix.env.action }}
      PROJECT: SwiftyOpenCC.xcodeproj
      SCHEME: SwiftyOpenCC-Package
      DESTINATION: ${{ matrix.env.destination }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Xcode Version
        run: xcodebuild -version
      - name: Build and Test
        run: |
          set -o pipefail
          xcodebuild "$ACTION" \
            -project "$PROJECT" \
            -scheme "$SCHEME" \
            -destination "$DESTINATION" | xcpretty

  SPMMac:
    strategy:
      matrix:
        xcode_version: ['12']
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Swift Version
        run: swift -version
      - name: Build and Test
        run: swift test

  SPMLinux:
    strategy:
      matrix:
        tag: ['5.3']
    runs-on: ubuntu-latest
    container:
      image: swift:${{ matrix.tag }}
    steps:
      - uses: actions/checkout@v1
      - run: git submodule update --init
      - name: Swift Version
        run: swift -version
      - name: Build and Test
        run: swift test
